### PR TITLE
Revised and corrected messed tables

### PR DESCRIPTION
**Pull request by sbenejam**

### CODE REVIEW

**Comment by mcallegari** [comment]
I found another one, question 8
https://docs.qlcplus.org/v4_ca/basics/questions-and-answers

**Comment by mcallegari** [comment]
Perhaps this is not right too
https://docs.qlcplus.org/v4_ca/main-window/dmx-dump
at "Bolca tots els canals"

**Comment by sbenejam** [comment]
I'll check it this afternoon. I'm looking for a good way to preview the
documents before sending them to avoid these errors. Perhaps I will install
a local web server to test before submitting the changes.


El dc., 3 de gen. 2024, 11:22, Massimo Callegari ***@***.***>
va escriure:

**Comment by sbenejam** [comment]
I checked some errors in the tables of the first translated files. For the
moment I will be doing the translations locally. And when I have reviewed
them, I'll send them to the repository.

Missatge de Santiago Benejam Torres ***@***.***> del dia dc., 3 de
gen. 2024 a les 11:30:

**Pull request merged**
